<a href="https://colab.research.google.com/github/arewadataScience/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> 

### **Arewa Data Science Academy**

#### **Deep Learning Cohort2.0**

##### Name: Yahya Abdurrazaq

##### Email: yahyarimi01@.com

##### Title: Week 1 Solution

### **Exercises Solution**

2. Create a random tensor with shape(7, 7).

In [1]:
import torch
import random

random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.4054, 0.8581, 0.3707, 0.8445, 0.2553, 0.8593, 0.1254],
        [0.4704, 0.9822, 0.1112, 0.8674, 0.7007, 0.9449, 0.4728],
        [0.1283, 0.1810, 0.9365, 0.7353, 0.8902, 0.1509, 0.0924],
        [0.8609, 0.9499, 0.6028, 0.9462, 0.4022, 0.9195, 0.0317],
        [0.2363, 0.0609, 0.9354, 0.4703, 0.4625, 0.4514, 0.7300],
        [0.4615, 0.3377, 0.6496, 0.1629, 0.0490, 0.6178, 0.2586],
        [0.5019, 0.9761, 0.7034, 0.9896, 0.4561, 0.8404, 0.2958]])

3.  Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [2]:
random_tensor_2 = torch.rand(1, 7)
random_tensor_2_trans = random_tensor_2.T

result = torch.matmul(random_tensor, random_tensor_2_trans)
result

tensor([[2.3162],
        [3.1335],
        [1.6219],
        [2.6792],
        [1.9856],
        [1.4121],
        [2.8612]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [3]:
RANDOM_SEED=0

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(1, 7)
random_tensor_B = random_tensor_B.T

result_2 = random_tensor_A @ random_tensor_B
result_2, result_2.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [4]:
torch.cuda.manual_seed(0)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [5]:
RANDOM_SEED = 1234

!nvidia-smi
torch.cuda.is_available()

torch.cuda.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(2, 3, device='cpu')

torch.random.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(2, 3, device='cpu')

random_tensor_C, random_tensor_D

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


(tensor([[0.8964, 0.4556, 0.6323],
         [0.3489, 0.4017, 0.0223]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [6]:
result_3 = torch.matmul(random_tensor_C, random_tensor_D.T)
result_3, result_3.device, result_3.shape

(tensor([[0.3734, 0.7983],
         [0.1774, 0.1670]]),
 device(type='cpu'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7

In [7]:
maximum = torch.argmax(result_3)
minimum = torch.argmin(result_3)

maximum, minimum

(tensor(1), tensor(3))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [8]:
RANDOM_SEED=7

torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(1,1,1,10)

torch.random.manual_seed(RANDOM_SEED)
random_tensor_F = torch.rand(10)

random_tensor_E, random_tensor_E.shape, random_tensor_F, random_tensor_F.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))