<a href="https://colab.research.google.com/github/arewadataScience/ArewaDS-Deep-Learning/blob/main/Part_1_Deep_Learning_with_Pytorch/week1/week_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> 

### **Arewa Data Science Academy**

#### **Deep Learning Cohort2.0**

##### Name: Yahya Abdurrazaq

##### Email: yahyarimi01@.com

##### Title: Week 1 Solution

### **Exercises Solution**

2. Create a random tensor with shape(7, 7).

In [4]:
import torch
import random

random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.3205, 0.0299, 0.0416, 0.3861, 0.3843, 0.5918, 0.4749],
        [0.2777, 0.4252, 0.5363, 0.3184, 0.5247, 0.1867, 0.3835],
        [0.6627, 0.2282, 0.0371, 0.2491, 0.7597, 0.0250, 0.2968],
        [0.0266, 0.9683, 0.0716, 0.3822, 0.6271, 0.9164, 0.1989],
        [0.0606, 0.9696, 0.9433, 0.5076, 0.3526, 0.6725, 0.4309],
        [0.6936, 0.4018, 0.7487, 0.7740, 0.4409, 0.1899, 0.6568],
        [0.2208, 0.4101, 0.0415, 0.7846, 0.3151, 0.2563, 0.2151]])

3.  Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [12]:
random_tensor_2 = torch.rand(1, 7)
random_tensor_2_trans = random_tensor_2.T

result = torch.matmul(random_tensor, random_tensor_2_trans)
result

tensor([[1.2446],
        [1.2706],
        [1.0188],
        [2.2646],
        [2.1633],
        [1.6977],
        [1.4601]])

4. Set the random seed to 0 and do 2 & 3 over again.

In [24]:
RANDOM_SEED=0

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_A = torch.rand(7, 7)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_B = torch.rand(1, 7)
random_tensor_B = random_tensor_B.T

result_2 = random_tensor_A @ random_tensor_B
result_2, result_2.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [25]:
torch.cuda.manual_seed(0)

6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [39]:
RANDOM_SEED = 1234

!nvidia-smi
torch.cuda.is_available()

torch.cuda.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(2, 3, device='cpu')

torch.random.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(2, 3, device='cpu')

random_tensor_C, random_tensor_D

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


(tensor([[0.7749, 0.8208, 0.2793],
         [0.6817, 0.2837, 0.6567]]),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]))

7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [42]:
result_3 = torch.matmul(random_tensor_C, random_tensor_D.T)
result_3, result_3.device, result_3.shape

(tensor([[0.4249, 0.5276],
         [0.3044, 0.7266]]),
 device(type='cpu'),
 torch.Size([2, 2]))

8. Find the maximum and minimum values of the output of 7

In [43]:
maximum = torch.argmax(result_3)
minimum = torch.argmin(result_3)

maximum, minimum

(tensor(3), tensor(2))

10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [48]:
RANDOM_SEED=7

torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(1,1,1,10)

torch.random.manual_seed(RANDOM_SEED)
random_tensor_F = torch.rand(10)

random_tensor_E, random_tensor_E.shape, random_tensor_F, random_tensor_F.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))